##mdp data
uint32 width
uint32 height
uint32 num_features
float64 discount
float64 confidence
float64 alpha
float64 delta
float64 epsilon
uint32[] initial_states
uint32[] terminal_states
FloatVector[] state_features
##demo data
StateAction[] demonstration
---
uint32[] policy
string status
uint32 query_state
